#!//usr/bin/perl

use URI::Escape qw( uri_unescape );

$tr="rotate&list=pbw&name=.pbw%2Fwnbr-2019.jpg&r=270";
$tm="names&all&host=lenovo&list=pbw";
$tf="get&host=lenovo&list=&name=Barb/IMG_8501.jpg&xy&w=600&h=888";
$tf="get&host=lenovo&list=pbw&name=.pbw%2FWwW.Wallpapers2012.com__+%28WwW.Wallpapers2012.com__7%29.jpg&w=1600&h=2560&r=0";
$query = $ENV{"QUERY_STRING"};
$type = "get";
$hidden = "";
$maxw = 2048;
$maxh = 2048;
$rotate = 0;
$xy = 0;
$host = "default";
$list = "";
$name = "";
$text = "";
$delta = 1;
$NOCACHE = 1;
$fit = "fit";

$DIR = "Books/Frame/";
$DLIST = ".files";

@tokens = split(/&/, $query);
foreach my $t (@tokens) {
	($type = $t)				if $t =~ /^get/;
	($type = $t)				if $t =~ /^names/;
	($type = $t)				if $t =~ /^title/;
	($type = $t)				if $t =~ /^delete/;
	($type = $t)				if $t =~ /^rotate/;
	($hidden = $t)				if $t =~ /^all/;
	($xy = 1)				if $t =~ /^xy/;
	($maxw = $t) =~ s/w=//			if $t =~ /^w=/;
	($maxh = $t) =~ s/h=//			if $t =~ /^h=/;
	($rotate = $t) =~ s/r=//		if $t =~ /^r=/;
	($host = $t) =~ s/host=//		if $t =~ /^host=/;
	($list = $t) =~ s/list=//		if $t =~ /^list=/;
	($name = $t) =~ s/name=//		if $t =~ /^name=/;
	($text = $t) =~ s/text=// 		if $t =~ /^text=/;
	($NOCACHE = 0) =~ s/cache//		if $t =~ /^cache/;
}

$name = &sanitize($name);
$text = &sanitize($text);
$host = "default"		if $host eq "";
$host = $host . "-" . $list	if $list ne "";
$DLIST = $DLIST . "-" . $list	if $list ne "";

#  Image operations
#
get_image($host, $name)	if $type eq "get";
del_image($name, )		if $type eq "delete";
set_title($name, $text)		if $type eq "title";
rot_image($name, $rotate)	if $type eq "rotate";

#  List Operations
#
get_names()			if $type eq "names";

sub out_line
{
	local ($t,$l) = @_;
	local ($n);

	$n = pack 'V',length($l) + 1;
	print $n;
	print $t.$l;
}

sub get_names
{
	local ($n,$gen,$ts,$dh,$dir,$entry);

	print <<END;
Content-type: application/octet-stream

END

	open F, $DIR . $DLIST;
	$gen = <F>;
	chop $gen;
	&out_line("G", $gen);
	while (<F>) {
		chop;
		$dir = $_;
		opendir($dh, $DIR . $dir) || last;
		while (readdir $dh) {
			next		if $_ eq ".";
			next		if $_ eq "..";
			$entry = $dir . "/" . $_;
			$ts = (stat($DIR . $entry))[9];
			&out_line("F", $ts . ":" . $entry);
		}
		closedir $dh;
	}
	close F;
	&out_line("E", $gen);
}

sub get_image
{
	local ($h,$n) = @_;
	local ($r,$t,$dim,$gen,$name,$F);

	print <<END;
Content-type: application/octet-stream

END

	$gen = &get_generation();

	if ($fit eq "full") {
		$cmd = "<$DIR$n";
	} else {
		if ($fit eq "screen") {
			$suf = "\\>";
		} elsif ($fit eq "stretch") {
			$suf = "!";
		} elsif ($fit = "fit") {
			$suf = "";
		}
		$r = "";
		$r = "-rotate $rotate"		if $rotate;
		$cmd = "convert \"$DIR$n\" $r -resize " . $maxw . "x" . $maxh . $suf . " -|";
	}
	$name = $n;
	$name =~ s/\//_/g;
	binmode STDOUT;
	&out_line("F", $n);
	$t = $DIR . ".titles/" . $name;
	if (-f $t) {
		open F, $t;
		$title = <F>;
		chop $title;
		close F;
		&out_line("T", $title);
	}

	if ($xy) {
		$dim=`identify -format "%wx%h" "$DIR$n"`;
		&out_line("D", $dim);
	}
	&out_line("E", $gen);
	$F = cache_file($name, $cmd, $maxw, $maxh);
	print <$F>;
	close $F;
}

sub del_image
{
	local($n) = @_;
	local($i,$g,$gen,$lines);

	print <<END;
Content-type: application/octet-stream

END

	open F, "<$DIR" . "$DLIST";
	$g = <F>;
	chomp($g);
	$gen = $g + 1;
	$i = 0;
	while (<F>) {
		$lines[$i++] = $_;
	}
	close F;

	open F, ">$DIR" . "$DLIST";
	print F "$gen\n";
	foreach $line (@lines) {
		print F $line;
	}
	close F;

	unlink $DIR.$n;

	&out_line("E", "");
}

sub rot_image
{
	local($n, $r) = @_;
	local($suf,$gen);

	print <<END;
Content-type: application/octet-stream

END

	$suf = "$n";
	$suf =~ s/.*\.//;
	system("convert $DIR$n -rotate $r /tmp/$$.$suf; cp /tmp/$$.$suf $DIR$n; rm -f /tmp/$$.$suf");
	$gen = &get_generation();
	&out_line("E", $gen);
}

sub set_title
{
	local($n, $t) = @_;
	local($f,$gen);

	print <<END;
Content-type: application/octet-stream

END

	$n =~ s/\//_/g;
	$f = "$DIR" . ".titles/$n";
	open F, ">$f";
	print F "$t\n";
	close F;
	$gen = &get_generation();
	&out_line("E", $gen);
}

sub cache_file
{
	local ($f,$c,$w,$h) = @_;
	local ($I,$cdir);

	$cdir = $DIR . ".cache";
	if (! -d $cdir || $NOCACHE) {
		open $I, $c;
		binmode $I;
		return $I;
	}
	$cname = $cdir . "/" . $f . ":" . $w . "x" . $h . ":" . $rotate;
	$c = $c . "cat >$cname";
	system($c)		if ! -f $cname;
	open $I, "<$cname";
	binmode $I;
	return $I;
}

sub get_generation
{
	local ($g);

	open LIST, "$DIR" . $DLIST;
	$g = <LIST>;
	chop $g;
	close LIST;
	return $g;
}

sub sanitize
{
	local ($n) = @_;

	#
	# Android URL encodes a blank as + while Perl doesn't, go figure.
	#   Fortuantely, Android does encode a + so a simple substitution works
	#
	$n =~ s/\+/ /g;
	$n = uri_unescape($n);
	return $n;
}
