#!//usr/bin/perl

use URI::Escape qw( uri_unescape );

$tm="names&all&host=lenovo&list=lrg";
$td="delete&list=pbw&name=.pbw%2Fwnbr-2019.jpg";
$tf="get&host=lenovo&list=&name=Barb/IMG_8501.jpg&xy&w=600&h=888";
$query = $ENV{"QUERY_STRING"};
$type = "get";
$hidden = "";
$maxw = 2048;
$maxh = 2048;
$rotate = 0;
$xy = 0;
$host = "default";
$list = "";
$delta = 1;
$NOCACHE = 1;
$fit = "fit";

$DIR = "Books/Frame/";
$dirs = ".files";

@tokens = split(/&/, $query);
foreach my $t (@tokens) {
	($type = $t)				if $t =~ /^get/;
	($type = $t)				if $t =~ /^names/;
	($type = $t)				if $t =~ /^title/;
	($type = $t)				if $t =~ /^delete/;
	($hidden = $t)				if $t =~ /^all/;
	($xy = 1)				if $t =~ /^xy/;
	($maxw = $t) =~ s/w=//			if $t =~ /^w=/;
	($maxh = $t) =~ s/h=//			if $t =~ /^h=/;
	($rotate = $t) =~ s/r=//		if $t =~ /^r=/;
	($host = $t) =~ s/host=//		if $t =~ /^host=/;
	($list = $t) =~ s/list=//		if $t =~ /^list=/;
	($name = uri_unescape($t)) =~ s/name=//	if $t =~ /^name=/;
	($text = uri_unescape($t)) =~ s/text=// if $t =~ /^text=/;
	($NOCACHE = 0) =~ s/cache//		if $t =~ /^cache/;
}

$host = "default"		if $host eq "";
$host = $host . "-" . $list	if $list ne "";
$dirs = $dirs . "-" . $list	if $list ne "";

#  Image operations
#
get_image($host, $dirs, $name)	if $type eq "get";
del_image($name, $dirs)		if $type eq "delete";
set_title($name, $text)		if $type eq "title";

#  List Operations
#
get_names($dirs)		if $type eq "names";

sub out_line
{
	local ($t,$l) = @_;
	local ($n);

	$n = pack 'V',length($l) + 1;
	print $n;
	print $t.$l;
}

sub get_names
{
	local ($f) = @_;
	local ($n,$gen,$ts,$dh,$dir,$entry);

	print <<END;
Content-type: application/octet-stream

END

	open F, $DIR . $f;
	$gen = <F>;
	chop $gen;
	&out_line("G", $gen);
	while (<F>) {
		chop;
		$dir = $_;
		opendir($dh, $DIR . $dir) || last;
		while (readdir $dh) {
			next		if $_ eq ".";
			next		if $_ eq "..";
			$entry = $dir . "/" . $_;
			$ts = (stat($DIR . $entry))[9];
			&out_line("F", $ts . ":" . $entry);
		}
		closedir $dh;
	}
	close F;
	&out_line("E", $gen);
}

sub get_image
{
	local ($h,$d,$n) = @_;
	local ($r,$t,$dim,$gen,$name,$F);

	print <<END;
Content-type: application/octet-stream

END

	open F, "$DIR" . $d;
	$gen = <F>;
	chop $gen;
	close F;

	if ($fit eq "full") {
		$cmd = "<$DIR$n";
	} else {
		if ($fit eq "screen") {
			$suf = "\\>";
		} elsif ($fit eq "stretch") {
			$suf = "!";
		} elsif ($fit = "fit") {
			$suf = "";
		}
		$r = "";
		$r = "-rotate $rotate"		if $rotate;
		$cmd = "convert \"$DIR$n\" $r -resize " . $maxw . "x" . $maxh . $suf . " -|";
	}
	$name = $n;
	$name =~ s/\//_/g;
	binmode STDOUT;
	&out_line("F", $n);
	$t = $DIR . ".titles/" . $name;
	if (-f $t) {
		open F, $t;
		$title = <F>;
		chop $title;
		close F;
		&out_line("T", $title);
	}

	if ($xy) {
		$dim=`identify -format "%wx%h" "$DIR$n"`;
		&out_line("D", $dim);
	}
	&out_line("E", $gen);
	$F = cache_file($name, $cmd, $maxw, $maxh);
	print <$F>;
	close $F;
}

sub del_image
{
	local($n,$d) = @_;
	local($i,$g,$gen,$lines);

	print <<END;
Content-type: application/octet-stream

END

	open F, "<$DIR" . "$d";
	$g = <F>;
	chomp($g);
	$gen = $g + 1;
	$i = 0;
	while (<F>) {
		$lines[$i++] = $_;
	}
	close F;

	open F, ">$DIR" . "$d";
	print F "$gen\n";
	foreach $line (@lines) {
		print F $line;
	}
	close F;

	unlink $DIR.$n;

	&out_line("E", "");
}

sub set_title
{
	local($n, $t) = @_;
	local($f);

	print <<END;
Content-type: application/octet-stream

END

	$n =~ s/\//_/g;
	$f = "$DIR" . ".titles/$n";
	open F, ">$f";
	print F "$t\n";
	close F;
	&out_line("E", "");
}

sub cache_file
{
	local ($f,$c,$w,$h) = @_;
	local ($I,$cdir);

	$cdir = $DIR . ".cache";
	if (! -d $cdir || $NOCACHE) {
		open $I, $c;
		binmode $I;
		return $I;
	}
	$cname = $cdir . "/" . $f . ":" . $w . "x" . $h . ":" . $rotate;
	$c = $c . "cat >$cname";
	system($c)		if ! -f $cname;
	open $I, "<$cname";
	binmode $I;
	return $I;
}
