#!/bin/bash

cat >/tmp/$$.f

FROM=`cat /tmp/$$.f | grep "From:"`
SUBJ=`cat /tmp/$$.f | grep "Subject:"`

PBW=`expr "$SUBJ" : '\(Subject: pbw:\).*'`
if [ "$PBW" != "Subject: pbw:" ]
then
	/bin/sed -e "s/^To:.*/To: bjgifford.150@photoshareframe.com/" /tmp/$$.f | /usr/sbin/sendmail -i bjgifford.150@photoshareframe.com
fi

ssh isis bin/save_photo \"$FROM\" \"$SUBJ\" </tmp/$$.f
rm /tmp/$$.f
